#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2

[[blocks]]
type = 'rprompt'
overflow = 'hidden'

[[blocks.segments]]
type = 'executiontime'
style = 'plain'
foreground = 'p:yellow'
background = 'transparent'
template = '{{ .FormattedMs }}'

[[blocks.segments]]
type = 'time'
style = 'plain'
foreground = 'white'

[blocks.segments.properties]
time_format = "15:04:05"

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = 'p:green'
    template = '{{ .UserName }}@{{ .HostName }} '

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = 'p:green'
    template = '{{ .Path }} '

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    template = 'git:{{ if or (.Working.Changed) (.Staging.Changed) (gt .StashCount 0) }}<p:red>{{ .HEAD }}</>{{ else }}{{ .HEAD }}{{ end }}{{ if .Staging.Changed }} <p:orange>{{ .Staging.String }}</>{{ end }}{{ if .Working.Changed }} <white>{{ .Working.String }}</>{{ end }}'

    [blocks.segments.properties]
      branch_icon = ''
      fetch_status = true


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = 'p:green'
    foreground_templates = ['{{ if gt .Code 0 }}#42a9ff{{ end }}']
    template = '> '

    [blocks.segments.properties]
      always_enabled = true

[palette]
green = '#b8bb26'
yellow = '#fabd2f'
orange = '#fe8019'
blue = '#83a598'
red = '#fb4934'
